name: Feature Request
description: Suggest a new feature or enhancement
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting an improvement.

  - type: dropdown
    id: plugin
    attributes:
      label: Target Plugin
      description: Which plugin should this feature be added to?
      options:
        - fs-dev
        - contextd
        - fs-design
        - New plugin
        - Not sure
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New skill
        - New command
        - New agent
        - Enhancement to existing feature
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What feature do you want?
      placeholder: As a user, I want...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Currently, I have to...

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: The feature should...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've thought about

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 - Critical need
        - P1 - High priority
        - P2 - Medium priority
        - P3 - Nice to have
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute this feature
        - label: I need help implementing this
